### ISSUE TITLE
xterm does not fill the parent container after navigation

### ISSUE THREAD

**Issue by mvysny** [FlowingCode/XTermConsoleAddon#35]
Navigating to a route with the XTerm component somehow breaks the xterm layouting mechanism since for some reason the xterm will not fill its parent `<fc-xterm>` element:

![bug](https://user-images.githubusercontent.com/254091/146733997-ac3759fa-ba0e-4502-ae2c-b01b89eb127a.png)

After the browser window is resized (or JS dev console is opened), everything seems to be fixed properly and now the terminal properly fills in the parent `<fc-xterm>` element.

## Steps to reproduce

Paste the following files into the Skeleton Starter Flow example project, using Vaadin 21.0.9:

MainLayout.java:
```java
package org.vaadin.example;

import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.RouterLayout;

public class MainLayout extends VerticalLayout implements RouterLayout {
    public MainLayout() {
        add(new Button("XTerm", e -> UI.getCurrent().navigate(XTermView.class)));
    }
}
```

 MainView.java
```java
package org.vaadin.example;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route(value = "", layout = MainLayout.class)
public class MainView extends VerticalLayout {
}
```

XTermView.java
```java
package org.vaadin.example;

import com.flowingcode.vaadin.addons.xterm.*;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route(value = "xterm", layout = MainLayout.class)
public class XTermView extends VerticalLayout {

    public XTermView() {
        setSizeFull();
        final XTerm xterm = new XTerm();
        xterm.setSizeFull();
        add(new HorizontalLayout(new Button("Foo")));
        addAndExpand(xterm);
        add(new HorizontalLayout(new Button("Bar")));
        TerminalHistory.extend(xterm);
        new Echo(new PreserveStateAddon(xterm), xterm);
    }

    public static class Echo {
        public Echo(ITerminal terminal, ITerminalConsole console) {
            console.setPrompt("ECHO> ");
            console.writePrompt();
            console.addLineListener(e -> {
               terminal.writeln("got: " + e.getLine());
                console.writePrompt();
            });
        }
    }
}
```

Simply run the app, then press the "XTerm" button to navigate to XTermView.

**Comment by javier-godoy** [comment]
Please add a call to `xterm.fit()` in the constructor (see example [here](https://github.com/FlowingCode/XTermConsoleAddon/blob/04ac96aaf2b181d911c9a2f0441f6ace283c97c5/src/test/java/com/flowingcode/vaadin/addons/xterm/XtermDemoView.java#L121)).

I didn't add that into the default initialization since fit behavior is provided by [xterm-addon-fit](https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-fit) and not by the core xterm.js library.

**Comment by mvysny** [comment]
Unfortunately, calling `xterm.fit()` both from constructor and from an attach listener doesn't seem to fix the issue:

```java
    public XTermView() {
        setSizeFull();
        final XTerm xterm = new XTerm();
        xterm.setSizeFull();
        xterm.focus();
        xterm.fit();
        addAttachListener( e -> xterm.fit());
        add(new HorizontalLayout(new Button("Foo")));
        addAndExpand(xterm);
        add(new HorizontalLayout(new Button("Bar")));
        TerminalHistory.extend(xterm);
        new Echo(new PreserveStateAddon(xterm), xterm);
    }
```

The XTerm "blinks" (shows temporarily with proper full width), but then it shrinks in width as shown in the above screenshot.

**Comment by javier-godoy** [comment]
That example reproduces the issue. The API seems to be used correctly.
