### ISSUE TITLE
PreserveStateAddon issues when using a prompt

### ISSUE THREAD

**Issue by jdewaen** [FlowingCode/XTermConsoleAddon#50]
I have found another issue, this time with the PreserveStateAddon. The core issue seems to be that the last (unsubmitted) prompt is also kept in the buffer. This looks visually fine, but for some reason it is considered part of the user input, even if the correct prompt is set before the preserved state is applied. My hypothesis is that this is because that final prompt isn't actually written with the `writePrompt` function on the client side, but I can't really confirm that given the complexity of xterm.js.

I have made a fork with a modified demo view that illustrates this issue: https://github.com/datadobi/XTermConsoleAddon/tree/preserve_state_demo

I have two ways to reproduce the issue:

1:
- Run the demo. The terminal should appear with a "toggle terminal" button at the top
- Click toggle terminal. The terminal should disappear
- Click toggle terminal again, the terminal will reappear.
- Enter a command, or press enter directly. You'll get the following error: `Unknown command: [user@xterm`.

2:
- Run the demo. The terminal should appear with a "toggle terminal" button at the top
- Run a few commands to fill the history
- Click toggle terminal. The terminal should disappear
- Click toggle terminal again, the terminal will reappear.
- Press the up button: the most recent command will apear
- Press the down button: the prompt will appear twice

I will open a pull request for a potential fix for this issue. It basically avoids writing the prompt to the buffer immediately, but waits until a line gets submitted. This means that we don't have a dangling prompt at the end of the buffer to get misinterpreted. To show the prompt as expected, `writePrompt` is called after writing the buffer when reattaching xterm. As far as I can see, this matches the old behavior exactly minus the issue. You can merge the fix branch onto the demo branch to quickly see the fix in action.

**Comment by javier-godoy** [comment]
The approach is correct. `writePrompt` is an special commands that prints the prompt in the console, and remembers that the prompt has been printed, so that it's not considered part of the current logical line when the user presses <kbd>Enter</kbd>.

**Comment by jdewaen** [comment]
@javier-godoy Thank you for integrating these fixes. One last thing: The 2.0.3 release hasn't been added to the Vaadin addon directory ( https://vaadin.com/directory/component/xterm-console-addon ) yet. Could you bring that up-to-date?

Thank you.

**Comment by javier-godoy** [comment]
@jdewaen Hello. It should be available now from the directory. Can you please check again?

Regards

**Comment by jdewaen** [comment]
It is now available, thanks.
