### ISSUE TITLE
(Vaadin 24) XTerm Addon not working

### ISSUE THREAD

**Issue by Gamer08YT** [FlowingCode/XTermConsoleAddon#81]
![grafik](https://github.com/FlowingCode/XTermConsoleAddon/assets/31771657/7992711d-0529-4d26-9d70-f417ba501f30)

![grafik](https://github.com/FlowingCode/XTermConsoleAddon/assets/31771657/dca3cc96-878d-4783-9d80-83db7543f208)

`        XTerm xterm = new XTerm();
        xterm.writeln("Hello world.\n\n");
        xterm.setCursorBlink(true);
        xterm.setCursorStyle(ITerminalOptions.CursorStyle.UNDERLINE);

        xterm.setSizeFull();

        xterm.setVisible(true);
        xterm.writeln("Hello");
        xterm.writeln("YES");

        TerminalHistory.extend(xterm);

        primary.add(menu);
        primary.add(xterm);`

**Comment by javier-godoy** [comment]
Hello. Please take a look at https://github.com/FlowingCode/XTermConsoleAddon#special-configuration-when-using-spring and verify whether `com.flowingcode` is whitelisted.
