### ISSUE TITLE
Compilation error in Vaadin 24.3.0 (incomatibility with newer version of Lit)

### ISSUE THREAD

**Issue by gbi** [FlowingCode/XTermConsoleAddon#82]
The compilation of the frontend fails with the following error:
```
[ERROR] "customElement" is not exported by "node_modules/lit-element/index.js", imported by "frontend/generated/jar-resources/fc-xterm/xterm.ts".  
[ERROR] file: frontend/generated/jar-resources/fc-xterm/xterm.ts:20:9  
[ERROR] 18:  * #L%  
[ERROR] 19:  */  
[ERROR] 20: import { customElement } from 'lit-element';
[ERROR]              ^
[ERROR] 21: 
[ERROR] 22: import { XTermElement } from './xterm-element';
```

The compilation is successful with Vaadin 24.2.5.

I think, that I have traced the error down to the following:
With the update of Vaadin to version 24.3.0 also comes the update of Vaadin Web Components to version 24.3.0 (see [Vaadin 24.3.0 Changelog](https://github.com/vaadin/platform/releases/tag/24.3.0)). The new version of Vaadin Web Components bumps Lit to version 3.0.0 (see [Vaadin Web Components Changelog](https://github.com/vaadin/web-components/releases/tag/v24.3.0)). Since Lit 3.0 the re-export of decorators from lit-element is removed (see [Lit 3 upgrade guide](https://lit.dev/docs/releases/upgrade/#removed-re-export-decorators)). There, it is stated that 'customElement' is not exported by 'lit-element' anymore.

The solution provided in the upgrade guide is to change the line 20 from
`import { customElement } from 'lit-element';`
to
`import { customElement } from 'lit/decorators.js';`

## Build Environment
 - Maven
 - Java 17
 - node.js v20.10.0
 - Vaadin 24.3.0
 - XTermConsoleAddon 2.2.0

**Comment by finaris-cs** [comment]
Same problem here, works with Vaadin 24.2.1, but not with 24.3.2.
Is there already an estimation when there could be a fix for this?

**Comment by javier-godoy** [comment]
Hello. Sorry for the delay. @gbi is correct. I had updated our demo environment to use 24.3 but a dependency with Lit 2.5 leaked into it. I'll try to address this issue ASAP.

**Comment by javier-godoy** [comment]
Thanks for reporting this issue. The fix has been pushed to 3.0.0-SNAPSHOT. We decided to go with a new major version for Vaadin 24.3, since XTermConsoleAddon 2.x claims compatibility with Vaadin 22 to 24.2.

You can use the snapshot by adding the following repository to your POM file: https://maven.flowingcode.com/snapshots/
The release may take a while because we are currently experiencing some issues in our release pipeline.

**Comment by gbi** [comment]
Thank you very much for the fast reaction and fix!

**Comment by jdewaen** [comment]
@javier-godoy Any update on the timing of version 3.0.0 ?

**Comment by javier-godoy** [comment]
Uh oh, this one slipped under our radar. I've reopened it to make sure we give it proper attention during our next weekly meeting  (We have public holidays both this and next week. I'll push for a release once I return to the office.)

**Comment by KingFalse** [comment]
@javier-godoy I'm really looking forward to the release of version 3.0, it's incredibly useful.

**Comment by javier-godoy** [comment]
> @javier-godoy I'm really looking forward to the release of version 3.0, it's incredibly useful.

Thanks :)

I have the release in my to-do list. As per our process, I require a colleague to approve it. However, we've had two consecutive three-day working weeks because of public holidays, and everyone's now rushing to catch up on the work that piled up.

**Comment by javier-godoy** [comment]
Version 3.0.0 has been released https://vaadin.com/directory/component/xterm-console-addon/3.0.0
